// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using candidate.Models;

#nullable disable

namespace candidate.Migrations
{
    [DbContext(typeof(r53_candidateDbContext))]
    [Migration("20230623083727_ScriptB")]
    partial class ScriptB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("candidate.Models.Candidate", b =>
                {
                    b.Property<int>("CandidateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CandidateId"), 1L, 1);

                    b.Property<string>("CandidateName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<bool>("Fresher")
                        .HasColumnType("bit");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("CandidateId");

                    b.ToTable("Candidate", (string)null);
                });

            modelBuilder.Entity("candidate.Models.CandidateSkill", b =>
                {
                    b.Property<int>("CandidateSkillsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CandidateSkillsId"), 1L, 1);

                    b.Property<int?>("CandidateId")
                        .HasColumnType("int");

                    b.Property<int?>("SkillsId")
                        .HasColumnType("int");

                    b.HasKey("CandidateSkillsId")
                        .HasName("PK__Candidat__717B8D26DA62707C");

                    b.HasIndex("CandidateId");

                    b.HasIndex("SkillsId");

                    b.ToTable("CandidateSkills");
                });

            modelBuilder.Entity("candidate.Models.Skill", b =>
                {
                    b.Property<int>("SkillsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkillsId"), 1L, 1);

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("SkillsId")
                        .HasName("PK__Skills__95A17ED5E4371EE7");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("candidate.Models.CandidateSkill", b =>
                {
                    b.HasOne("candidate.Models.Candidate", "Candidate")
                        .WithMany("CandidateSkills")
                        .HasForeignKey("CandidateId")
                        .HasConstraintName("FK__Candidate__Candi__286302EC");

                    b.HasOne("candidate.Models.Skill", "Skills")
                        .WithMany("CandidateSkills")
                        .HasForeignKey("SkillsId")
                        .HasConstraintName("FK__Candidate__Skill__29572725");

                    b.Navigation("Candidate");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("candidate.Models.Candidate", b =>
                {
                    b.Navigation("CandidateSkills");
                });

            modelBuilder.Entity("candidate.Models.Skill", b =>
                {
                    b.Navigation("CandidateSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
